[project]
name = "rag-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "faiss-cpu>=1.15.1",
    "fastapi>=0.142.2",
    "langchain>=1.4.3",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.7",
    "litellm>=1.104.0",
    "markdown>=3.11",
    "pypdf>=6.19.0",
    "python-multipart>=0.0.32",
    "unstructured>=0.27.16",
    "uvicorn>=0.54.0",
]
